# Tools
brew "cloc"
# brew "direnv"
# brew "mdbook"

# Docker
cask "docker"

# NodeJS
# brew "node"

# Go
# brew "go"

# Rust
# brew "rust"

# Java / Scala
# cask "intellij-idea-ce"
# cask "openjdk"
# brew "sbt"
# brew "scala"

# OCaml
# brew "ocaml"
# brew "opam"

# Python
# brew "yapf"

# AWS
# brew "awscli"
# tap "hashicorp/tap"
# brew "hashicorp/tap/terraform"

# SMT
# brew "z3"

# SQL
# cask "sequel-pro"

# VSCode
cask "visual-studio-code"

vscode "bierner.github-markdown-preview"
vscode "juanblanco.solidity"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "tintinweb.vscode-inline-bookmarks"
vscode "vscodevim.vim"
