tap "homebrew/bundle"
tap "homebrew/cask"

# GNU utils
brew "coreutils"
brew "gnu-sed"
brew "watch"

# better (fuzzy) find
brew "fd"
brew "fzf"

# better grep
brew "grep"
brew "ripgrep"

# Git
brew "git"

# OCaml
brew "ocaml"
brew "opam"

# Python
brew "yapf"

# Shell
brew "zsh"

# Z3
brew "z3"

cask "adobe-acrobat-reader"
cask "bettertouchtool"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "hammerspoon"
cask "karabiner-elements"
cask "kitty"
cask "macvim"
cask "notion"
cask "pine"
cask "rectangle"
cask "skim"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "ticktick"
cask "whatsapp"
cask "zoom"
